# Generated by Django 4.2.30 on 2026-05-30 00:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('obras', '0001_initial'),
        ('exposicoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inteira', 'Inteira'), ('meia', 'Meia'), ('cortesia', 'Cortesia')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('utilizado', 'Utilizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('exposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='exposicoes.exposicao')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='contas.visitante')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'db_table': 'museu_ingresso',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('exposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='exposicoes.exposicao')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='contas.visitante')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'museu_reserva',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('ingresso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='visitacao.ingresso')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='visitacao.reserva')),
                ('restauracao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='obras.restauracao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'museu_pagamento',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('exposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='exposicoes.exposicao')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='contas.visitante')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'museu_avaliacao',
            },
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('visitante', 'exposicao'), name='unique_avaliacao_por_visitante'),
        ),
    ]
