# Generated by Django 4.2.30 on 2026-05-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tecnica', models.CharField(max_length=100)),
                ('ano_criacao', models.PositiveIntegerField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='categorias.categoriaobra')),
            ],
            options={
                'verbose_name': 'Obra de Arte',
                'verbose_name_plural': 'Obras de Arte',
                'db_table': 'museu_obraarte',
            },
        ),
        migrations.CreateModel(
            name='Restauracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restauracoes', to='contas.funcionario')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauracoes', to='obras.obraarte')),
            ],
            options={
                'verbose_name': 'Restauração',
                'verbose_name_plural': 'Restaurações',
                'db_table': 'museu_restauracao',
            },
        ),
        migrations.CreateModel(
            name='CertificadoAutenticidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateField()),
                ('orgao_responsavel', models.CharField(max_length=200)),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='obras.obraarte')),
            ],
            options={
                'verbose_name': 'Certificado de Autenticidade',
                'verbose_name_plural': 'Certificados de Autenticidade',
                'db_table': 'museu_certificadoautenticidade',
            },
        ),
        migrations.CreateModel(
            name='ArtistaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('data_participacao', models.DateField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_artista', to='contas.artista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistas_obra', to='obras.obraarte')),
            ],
            options={
                'verbose_name': 'Participação do Artista',
                'verbose_name_plural': 'Participações dos Artistas',
                'db_table': 'museu_artistaobra',
                'unique_together': {('artista', 'obra')},
            },
        ),
    ]
