# Generated by Django 4.2.30 on 2026-05-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('encerrada', 'Encerrada')], default='planejada', max_length=20)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposicoes', to='galerias.galeria')),
            ],
            options={
                'verbose_name': 'Exposição',
                'verbose_name_plural': 'Exposições',
                'db_table': 'museu_exposicao',
            },
        ),
        migrations.CreateModel(
            name='ExposicaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('posicao_sala', models.CharField(max_length=100)),
                ('iluminacao_especial', models.CharField(blank=True, max_length=100)),
                ('status_conservacao', models.CharField(max_length=100)),
                ('estilo_obra', models.CharField(blank=True, max_length=100)),
                ('exposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_exposicao', to='exposicoes.exposicao')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposicoes_obra', to='obras.obraarte')),
            ],
            options={
                'verbose_name': 'Obra na Exposição',
                'verbose_name_plural': 'Obras na Exposição',
                'db_table': 'museu_exposicaoobra',
                'unique_together': {('exposicao', 'obra')},
            },
        ),
    ]
