# Generated by Django 4.2.30 on 2026-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('visitante', 'exposicao'), name='unique_avaliacao_por_visitante'),
        ),
    ]
